/**
 * Seed Data — 50 Real Loksewa-Style MCQ Questions
 * Covers 5 subjects with 10 questions each:
 * - Constitution (10)
 * - General Knowledge (10)
 * - Nepali Language (10)
 * - Current Affairs (10)
 * - Governance/Public Admin (10)
 *
 * All questions are authored with real Nepal-specific content
 * suitable for Loksewa (Public Service Commission) exam preparation.
 */

import type { Question } from '@/types/question'
import { initDB } from './schema'

const now = Date.now()

export const SEED_QUESTIONS: Question[] = [
  // ═══════════════════════════════════════════════════════════════
  // CONSTITUTION — 10 Questions (seed-001 to seed-010)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'seed-001',
    text: 'नेपालको संविधान २०७२ को प्रस्तावनामा "लोकतान्त्रिक लोकतन्त्र" शब्द कसले प्रस्ताव गरेका थिए?',
    options: [
      { id: 'A', text: 'सदानन्द दाहाल', isCorrect: false },
      { id: 'B', text: 'डा. रामबरण यादव', isCorrect: true },
      { id: 'C', text: 'पुष्पकमल दाहाल', isCorrect: false },
      { id: 'D', text: 'माधवकुमार नेपाल', isCorrect: false },
    ],
    explanation: 'संविधान २०७२ को प्रस्तावनामा "लोकतान्त्रिक लोकतन्त्र" शब्द प्रस्तावक सदस्य डा. रामबरण यादवले प्रस्ताव गरेका थिए। यो शब्द नेपालको संविधानमा विशेष महत्त्व बोकेको छ।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'constitution',
    chapter: 'प्रस्तावना',
    year: 2075,
    source: 'seed',
    tags: ['संविधान-२०७२', 'प्रस्तावना', 'संविधान सभा'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-002',
    text: 'नेपालको संविधान २०७२ अनुसार मौलिक हकको संख्या कति छ?',
    options: [
      { id: 'A', text: '२२', isCorrect: false },
      { id: 'B', text: '२३', isCorrect: false },
      { id: 'C', text: '३१', isCorrect: true },
      { id: 'D', text: '३५', isCorrect: false },
    ],
    explanation: 'नेपालको संविधान २०७२ को भाग ३ मा कुल ३१ वटा मौलिक हकहरू सूचीबद्ध छन्। यसअघिको अन्तरिम संविधान २०६७ मा २३ वटा मौलिक हक थिए।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'constitution',
    chapter: 'मौलिक हक',
    year: 2075,
    source: 'seed',
    tags: ['मौलिक हक', 'संविधान-२०७२', 'भाग-३'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-003',
    text: 'नेपालको संविधान २०७२ अनुसार राष्ट्रपतिको अवधि कति वर्ष हुन्छ?',
    options: [
      { id: 'A', text: '४ वर्ष', isCorrect: false },
      { id: 'B', text: '५ वर्ष', isCorrect: false },
      { id: 'C', text: '६ वर्ष', isCorrect: true },
      { id: 'D', text: '७ वर्ष', isCorrect: false },
    ],
    explanation: 'संविधान २०७२ को धारा ६४ अनुसार राष्ट्रपतिको कार्यकाल ६ वर्षको हुन्छ। उहाँ दुई पटकसम्म राष्ट्रपति बन्न सक्नुहुन्छ।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'constitution',
    chapter: 'कार्यपालिका',
    year: 2075,
    source: 'seed',
    tags: ['राष्ट्रपति', 'कार्यकाल', 'संविधान-२०७२'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-004',
    text: 'नेपालको संविधान २०७२ अनुसार प्रतिनिधि सभामा कति सदस्य हुन्छन्?',
    options: [
      { id: 'A', text: '२५०', isCorrect: false },
      { id: 'B', text: '२७५', isCorrect: true },
      { id: 'C', text: '३०५', isCorrect: false },
      { id: 'D', text: '३३०', isCorrect: false },
    ],
    explanation: 'संविधान २०७२ को धारा ८१ अनुसार प्रतिनिधि सभामा कुल २७५ सदस्य हुन्छन्। यसमा १६५ जना प्रत्यक्ष निर्वाचित र ११० जना समानुपातिक निर्वाचन प्रणालीबाट निर्वाचित हुन्छन्।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'constitution',
    chapter: 'संसद',
    year: 2076,
    source: 'seed',
    tags: ['प्रतिनिधि सभा', 'संसद', 'निर्वाचन'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-005',
    text: 'नेपालको संविधान अनुसार संसदीय समितिको संख्या कति छ?',
    options: [
      { id: 'A', text: '१५', isCorrect: false },
      { id: 'B', text: '१६', isCorrect: true },
      { id: 'C', text: '१८', isCorrect: false },
      { id: 'D', text: '२०', isCorrect: false },
    ],
    explanation: 'संविधान २०७२ को धारा ९३ अनुसार प्रतिनिधि सभामा कुल १६ वटा संसदीय समिति रहन्छन्। यसमा विशेष समिति र स्थायी समिति समावेश छन्।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'constitution',
    chapter: 'संसद',
    year: 2076,
    source: 'seed',
    tags: ['संसदीय समिति', 'प्रतिनिधि सभा', 'संसद'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-006',
    text: 'नेपालमा संवैधानिक परिषद्को गठन कति संख्यामा गरिएको छ?',
    options: [
      { id: 'A', text: '१', isCorrect: false },
      { id: 'B', text: '२', isCorrect: false },
      { id: 'C', text: '३', isCorrect: false },
      { id: 'D', text: '४', isCorrect: true },
    ],
    explanation: 'संविधान २०७२ अनुसार नेपालमा ४ वटा संवैधानिक निकायहरू छन्: सर्वोच्च अदालत, निर्वाचन आयोग, लोकसेवा आयोग, र लेखा तथा महालेखा परीक्षण कार्यालय। अन्य आयोगहरू पनि संवैधानिक अंगको रूपमा स्थापित छन्।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'constitution',
    chapter: 'संवैधानिक अंगहरू',
    year: 2077,
    source: 'seed',
    tags: ['संवैधानिक निकाय', 'संविधान-२०७२'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-007',
    text: 'लोकसेवा आयोगका अध्यक्षको पदमा नियुक्ति को गर्छ?',
    options: [
      { id: 'A', text: 'राष्ट्रपति', isCorrect: false },
      { id: 'B', text: 'प्रधानमन्त्री', isCorrect: true },
      { id: 'C', text: 'संवैधानिक परिषद्', isCorrect: false },
      { id: 'D', text: 'संसदीय समिति', isCorrect: false },
    ],
    explanation: 'संविधान २०७२ को धारा २४२ अनुसार लोकसेवा आयोगको अध्यक्ष प्रधानमन्त्रीको सिफारिसमा संवैधानिक परिषद्ले नियुक्त गर्दछ।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'constitution',
    chapter: 'लोकसेवा आयोग',
    year: 2076,
    source: 'seed',
    tags: ['लोकसेवा आयोग', 'अध्यक्ष', 'नियुक्ति'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-008',
    text: 'नेपालको संविधान २०७२ अनुसार महिलाहरूको प्रतिशत संख्या संसदमा कति हुनुपर्छ?',
    options: [
      { id: 'A', text: '३३ प्रतिशत', isCorrect: true },
      { id: 'B', text: '२५ प्रतिशत', isCorrect: false },
      { id: 'C', text: '४० प्रतिशत', isCorrect: false },
      { id: 'D', text: '२० प्रतिशत', isCorrect: false },
    ],
    explanation: 'संविधान २०७२ मा महिलाको सहभागिता सुनिश्चित गर्न संघीय र प्रदेशस्तरीय संसदीय निर्वाचनमा कम्तिमा एक-तिहाइ (३३%) महिला उम्मेदवार हुनुपर्छ भन्ने व्यवस्था छ।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'constitution',
    chapter: 'मौलिक हक',
    year: 2077,
    source: 'seed',
    tags: ['महिला सहभागिता', 'संवैधानिक व्यवस्था', 'समानुपातिक'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-009',
    text: 'संविधान लागू हुन नसकेसम्मको लागि कुन अनुच्छेदले प्राविधिक सरकारको व्यवस्था गरेको छ?',
    options: [
      { id: 'A', text: 'अनुच्छेद २९५', isCorrect: true },
      { id: 'B', text: 'अनुच्छेद २९६', isCorrect: false },
      { id: 'C', text: 'अनुच्छेद २९७', isCorrect: false },
      { id: 'D', text: 'अनुच्छेद ३०१', isCorrect: false },
    ],
    explanation: 'संविधान २०७२ को अनुच्छेद २९५ अनुसार संविधान लागू हुन नसकेसम्मको लागि प्राविधिक सरकारको व्यवस्था गरिएको छ। यो अनुच्छेद संक्रमणकालीन व्यवस्थाको अंश हो।',
    type: 'mcq',
    difficulty: 'hard',
    subject: 'constitution',
    chapter: 'संवैधानिक अंगहरू',
    year: 2075,
    source: 'seed',
    tags: ['प्राविधिक सरकार', 'संक्रमणकाल', 'अनुच्छेद-२९५'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-010',
    text: 'नेपालको संविधान २०७२ अनुसार राज्यको निर्देशक सिद्धान्त कुन भागमा उल्लेख छ?',
    options: [
      { id: 'A', text: 'भाग ३', isCorrect: false },
      { id: 'B', text: 'भाग ४', isCorrect: true },
      { id: 'C', text: 'भाग ५', isCorrect: false },
      { id: 'D', text: 'भाग ६', isCorrect: false },
    ],
    explanation: 'संविधान २०७२ को भाग ४ (धारा ४५ देखि ५१ सम्म) मा राज्यको निर्देशक सिद्धान्तहरू उल्लेख छन्। यी सिद्धान्तहरू राज्यले पालना गर्नुपर्ने मार्गनिर्देशन हुन्।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'constitution',
    chapter: 'राज्यको निर्देशक सिद्धान्त',
    year: 2076,
    source: 'seed',
    tags: ['निर्देशक सिद्धान्त', 'संविधान-२०७२', 'भाग-४'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },

  // ═══════════════════════════════════════════════════════════════
  // GENERAL KNOWLEDGE — 10 Questions (seed-011 to seed-020)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'seed-011',
    text: 'नेपालको राष्ट्रिय फूल कुन हो?',
    options: [
      { id: 'A', text: 'सुनवाली (गोरखाली)', isCorrect: true },
      { id: 'B', text: 'जरासुनवाली', isCorrect: false },
      { id: 'C', text: 'चमेली', isCorrect: false },
      { id: 'D', text: 'लाली गुराँस', isCorrect: false },
    ],
    explanation: 'सुनवाली (Rhododendron) नेपालको राष्ट्रिय फूल हो। यो लिलासु रङ्गको फूल हुन्छ र उच्च पहाडी क्षेत्रमा पाइन्छ।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'general-knowledge',
    chapter: 'Nepal GK',
    year: 2075,
    source: 'seed',
    tags: ['राष्ट्रिय फूल', 'सुनवाली', 'नेपाल-पहिचान'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-012',
    text: 'नेपालको सबैभन्दा लामो नदी कुन हो?',
    options: [
      { id: 'A', text: 'कर्णाली', isCorrect: true },
      { id: 'B', text: 'कोशी', isCorrect: false },
      { id: 'C', text: 'गण्डकी', isCorrect: false },
      { id: 'D', text: 'महाकाली', isCorrect: false },
    ],
    explanation: 'कर्णाली नेपालको सबैभन्दा लामो नदी हो। यसको लम्बाई नेपाल भित्र लगभग ५०७ किलोमिटर छ। यो नदी तिब्बतबाट बगेर भारतको गङ्गासँग मिल्छ।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'general-knowledge',
    chapter: 'Nepal GK',
    year: 2076,
    source: 'seed',
    tags: ['नदी', 'कर्णाली', 'भूगोल'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-013',
    text: 'नेपालको कुल क्षेत्रफल कति वर्ग किलोमिटर छ?',
    options: [
      { id: 'A', text: '१,४७,१८१', isCorrect: true },
      { id: 'B', text: '१,५०,५५६', isCorrect: false },
      { id: 'C', text: '१,३५,५८५', isCorrect: false },
      { id: 'D', text: '१,६०,२३०', isCorrect: false },
    ],
    explanation: 'नेपालको कुल क्षेत्रफल १,४७,१८१ वर्ग किलोमिटर छ। यो विश्वको ९३ औँ सबैभन्दा ठूलो देश हो।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'general-knowledge',
    chapter: 'Nepal GK',
    year: 2075,
    source: 'seed',
    tags: ['क्षेत्रफल', 'नेपाल-भूगोल', 'सामान्य-ज्ञान'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-014',
    text: 'नेपालमा हुने सबैभन्दा ठूलो ताल कुन हो?',
    options: [
      { id: 'A', text: 'रारा ताल', isCorrect: false },
      { id: 'B', text: 'फोक्सुण्डो ताल', isCorrect: true },
      { id: 'C', text: 'फेवा ताल', isCorrect: false },
      { id: 'D', text: 'तिलिचो ताल', isCorrect: false },
    ],
    explanation: 'फोक्सुण्डो ताल नेपालको सबैभन्दा ठूलो ताल हो। यो डोल्पा जिल्लामा अवस्थित छ र यसको क्षेत्रफल लगभग ४९४ हेक्टर छ।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'general-knowledge',
    chapter: 'Nepal GK',
    year: 2076,
    source: 'seed',
    tags: ['ताल', 'फोक्सुण्डो', 'डोल्पा'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-015',
    text: 'इन्द्रजात्रा नेपालको कुन जातिले मनाउने प्रमुख चाड हो?',
    options: [
      { id: 'A', text: 'नेवार', isCorrect: true },
      { id: 'B', text: 'गुरुङ', isCorrect: false },
      { id: 'C', text: 'मगर', isCorrect: false },
      { id: 'D', text: 'राई', isCorrect: false },
    ],
    explanation: 'इन्द्रजात्रा काठमाडौंको प्रमुख चाड हो जुन नेवार समुदायले विशेष रूपमा मनाउँछन्। यो चाड भाद्र महिनाको शुक्ल पक्षमा मनाइन्छ।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'general-knowledge',
    chapter: 'Nepal GK',
    year: 2077,
    source: 'seed',
    tags: ['चाडपर्व', 'इन्द्रजात्रा', 'नेवार', 'संस्कृति'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-016',
    text: 'नेपालको राष्ट्रिय पंक्षी कुन हो?',
    options: [
      { id: 'A', text: 'मयूर (डाँफे)', isCorrect: true },
      { id: 'B', text: 'कालिज', isCorrect: false },
      { id: 'C', text: 'चिल', isCorrect: false },
      { id: 'D', text: 'भुँडेमाथिको', isCorrect: false },
    ],
    explanation: 'मयूर (Lophophorus / डाँफे) नेपालको राष्ट्रिय पंक्षी हो। यो हिमालय पहाडको उच्च भेगमा पाइन्छ।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'general-knowledge',
    chapter: 'Nepal GK',
    year: 2075,
    source: 'seed',
    tags: ['राष्ट्रिय पंक्षी', 'डाँफे', 'नेपाल-पहिचान'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-017',
    text: 'Lumbini नेपालको कुन जिल्लामा अवस्थित छ?',
    options: [
      { id: 'A', text: 'कपिलवस्तु', isCorrect: true },
      { id: 'B', text: 'नवलपरासी', isCorrect: false },
      { id: 'C', text: 'रूपन्देही', isCorrect: false },
      { id: 'D', text: 'बाँके', isCorrect: false },
    ],
    explanation: 'लुम्बिनी नेपालको कपिलवस्तु जिल्लामा अवस्थित छ। यो बुद्धको जन्मस्थलको रूपमा प्रसिद्ध छ र युनेस्को विश्व सम्पदा सूचीमा सूचीबद्ध छ।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'general-knowledge',
    chapter: 'Nepal GK',
    year: 2076,
    source: 'seed',
    tags: ['लुम्बिनी', 'बुद्ध', 'विश्व-सम्पदा', 'कपिलवस्तु'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-018',
    text: 'नेपाल एसियाको कुन अञ्चलमा पर्छ?',
    options: [
      { id: 'A', text: 'दक्षिण एसिया', isCorrect: true },
      { id: 'B', text: 'दक्षिण-पूर्व एसिया', isCorrect: false },
      { id: 'C', text: 'मध्य एसिया', isCorrect: false },
      { id: 'D', text: 'पूर्व एसिया', isCorrect: false },
    ],
    explanation: 'नेपाल दक्षिण एसियामा पर्छ। यो भारत र चीन (तिब्बत) बीच अवस्थित सानो भूपरिवेष्ठित राष्ट्र हो।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'general-knowledge',
    chapter: 'World GK',
    year: 2075,
    source: 'seed',
    tags: ['दक्षिण एसिया', 'नेपाल-अवस्थिति', 'भूराजनीति'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-019',
    text: 'नेपालको संस्कृतिमा "न्वागी" के हो?',
    options: [
      { id: 'A', text: 'पर्व मनाउने प्रक्रिया', isCorrect: false },
      { id: 'B', text: 'बालको मुण्डन संस्कार', isCorrect: true },
      { id: 'C', text: 'विवाह संस्कार', isCorrect: false },
      { id: 'D', text: 'नामकरण संस्कार', isCorrect: false },
    ],
    explanation: 'न्वागी नेवार समुदायमा बालको मुण्डन (केश खौर्ने) संस्कार हो। यो नेवार संस्कारको महत्त्वपूर्ण अंश हो।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'general-knowledge',
    chapter: 'Nepal GK',
    year: 2077,
    source: 'seed',
    tags: ['न्वागी', 'नेवार संस्कार', 'संस्कृति'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-020',
    text: 'सार्क (SAARC) को मुख्यालय कहाँ छ?',
    options: [
      { id: 'A', text: 'काठमाडौं', isCorrect: true },
      { id: 'B', text: 'दिल्ली', isCorrect: false },
      { id: 'C', text: 'ढाका', isCorrect: false },
      { id: 'D', text: 'इस्लामाबाद', isCorrect: false },
    ],
    explanation: 'दक्षिण एसियाली क्षेत्रीय सहयोग संगठन (SAARC) को मुख्यालय काठमाडौं, नेपालमा छ। यो ८ देशको क्षेत्रीय संगठन हो।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'general-knowledge',
    chapter: 'Organizations',
    year: 2076,
    source: 'seed',
    tags: ['SAARC', 'मुख्यालय', 'अन्तर्राष्ट्रिय संस्था'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },

  // ═══════════════════════════════════════════════════════════════
  // NEPALI LANGUAGE — 10 Questions (seed-021 to seed-030)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'seed-021',
    text: '"सुगाको हाँडी कानमा के होला?" भन्ने नेपाली उखानको अर्थ के हो?',
    options: [
      { id: 'A', text: 'गाउँलेको नियत नै खराब हुन्छ', isCorrect: false },
      { id: 'B', text: 'मानिसले गरेको वाचा नै खोस्ने हुन्छ', isCorrect: true },
      { id: 'C', text: 'जो कसैलाई छ त्यसैलाई लाग्छ', isCorrect: false },
      { id: 'D', text: 'उपयुक्त नभएको काम नगर्नु', isCorrect: false },
    ],
    explanation: 'यो उखानको अर्थ हो — मानिसले गरेको वाचा नै खोस्ने हुन्छ। सुगा आफ्नै हाँडीलाई बिर्सेर अरूको कानमा हेर्छ भन्ने अर्थ हुन्छ।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'nepali',
    chapter: 'साहित्य',
    year: 2076,
    source: 'seed',
    tags: ['उखान', 'नेपाली-साहित्य', 'लोककथा'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-022',
    text: '"आँखाको माया आँखैले, देखेको माया देखैले" कुन लेखकको कृति हो?',
    options: [
      { id: 'A', text: 'भवानी भिक्षु', isCorrect: false },
      { id: 'B', text: 'पारिजात', isCorrect: true },
      { id: 'C', text: 'लेखनाथ पौड्याल', isCorrect: false },
      { id: 'D', text: 'गोपालप्रसाद रिमाल', isCorrect: false },
    ],
    explanation: '"आँखाको माया आँखैले" नेपालका प्रसिद्ध साहित्यकार पारिजातको उपन्यास हो। यो नेपाली साहित्यको उत्कृष्ट कृतिमा पर्छ।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'nepali',
    chapter: 'साहित्य',
    year: 2075,
    source: 'seed',
    tags: ['पारिजात', 'उपन्यास', 'नेपाली-साहित्य'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-023',
    text: 'नेपाली भाषामा "वर्तमान काल" कति प्रकारका हुन्छन्?',
    options: [
      { id: 'A', text: '३ प्रकार', isCorrect: true },
      { id: 'B', text: '२ प्रकार', isCorrect: false },
      { id: 'C', text: '४ प्रकार', isCorrect: false },
      { id: 'D', text: '५ प्रकार', isCorrect: false },
    ],
    explanation: 'नेपाली व्याकरणमा वर्तमान कालका तीन प्रकार हुन्छन्: सामान्य वर्तमान, निरन्तर वर्तमान (रहेको छ), र पूर्ण वर्तमान (भइसकेको छ)।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'nepali',
    chapter: 'व्याकरण',
    year: 2076,
    source: 'seed',
    tags: ['लकार', 'वर्तमान काल', 'व्याकरण'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-024',
    text: '"मुनामदन" कुन लेखकको प्रसिद्ध महाकाव्य हो?',
    options: [
      { id: 'A', text: 'माधवप्रसाद घिमिरे', isCorrect: false },
      { id: 'B', text: 'शिरोमणि शर्मा', isCorrect: false },
      { id: 'C', text: 'लक्ष्मीप्रसाद देवकोटा', isCorrect: false },
      { id: 'D', text: 'सत्यमोहन जोशी', isCorrect: true },
    ],
    explanation: '"मुनामदन" सत्यमोहन जोशीको प्रसिद्ध महाकाव्य हो। यो नेपाली साहित्यको सबैभन्दा प्रसिद्ध महाकाव्य मानिन्छ।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'nepali',
    chapter: 'साहित्य',
    year: 2075,
    source: 'seed',
    tags: ['महाकाव्य', 'सत्यमोहन जोशी', 'मुनामदन'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-025',
    text: 'निम्न मध्ये कुन उपसर्ग होइन?',
    options: [
      { id: 'A', text: 'अ', isCorrect: false },
      { id: 'B', text: 'दु', isCorrect: false },
      { id: 'C', text: 'प्र', isCorrect: false },
      { id: 'D', text: 'ता', isCorrect: true },
    ],
    explanation: '"ता" उपसर्ग होइन, यो प्रत्यय हो। "अ", "दु", "प्र", "सु", "नि" आदि उपसर्ग हुन् जुन शब्दको अगाडि जोडिन्छन्। "ता" जस्ता प्रत्ययहरू शब्दको पछाडि जोडिन्छन्।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'nepali',
    chapter: 'व्याकरण',
    year: 2077,
    source: 'seed',
    tags: ['उपसर्ग', 'प्रत्यय', 'व्याकरण'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-026',
    text: '"रस" कुन छन्दमा लेखिएको गीतिकाव्य हो?',
    options: [
      { id: 'A', text: 'अन्यत्र', isCorrect: false },
      { id: 'B', text: 'विद्यावती', isCorrect: false },
      { id: 'C', text: 'सुमती', isCorrect: false },
      { id: 'D', text: 'गोपालप्रसाद रिमाल — "अबहाल मा"', isCorrect: false },
    ],
    explanation: '"रस" लेखनाथ पौड्यालको नेपाली भाषाको पहिलो गीतिकाव्य हो। यसमा दुई दर्जन गीतहरू समावेश छन्।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'nepali',
    chapter: 'साहित्य',
    year: 2076,
    source: 'seed',
    tags: ['गीतिकाव्य', 'लेखनाथ पौड्याल', 'रस'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-027',
    text: 'नेपाली भाषामा कारकको संख्या कति छ?',
    options: [
      { id: 'A', text: '५', isCorrect: false },
      { id: 'B', text: '६', isCorrect: false },
      { id: 'C', text: '७', isCorrect: false },
      { id: 'D', text: '८', isCorrect: true },
    ],
    explanation: 'नेपाली व्याकरणमा ८ वटा कारकहरू छन्: कर्ता, कर्म, करण, सम्प्रदान, अपादान, अधिकरण, लेखक, र सम्बोधन।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'nepali',
    chapter: 'व्याकरण',
    year: 2076,
    source: 'seed',
    tags: ['कारक', 'व्याकरण', 'नेपाली-व्याकरण'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-028',
    text: '"भानुभक्त" नेपाली भाषाको पिता किन भनिन्छ?',
    options: [
      { id: 'A', text: 'पहिलो नेपाली व्याकरण लेखन गरे', isCorrect: false },
      { id: 'B', text: 'पहिलो नेपाली कविता लेखन गरे', isCorrect: false },
      { id: 'C', text: 'रामायणको नेपालीमा अनुवाद गरे', isCorrect: false },
      { id: 'D', text: 'उपरोक्त सबै', isCorrect: true },
    ],
    explanation: 'आदिकवि भानुभक्त आचार्यलाई नेपाली भाषाको पिता मानिन्छ। उनले पहिलो नेपाली कविता, व्याकरण र रामायणको नेपाली अनुवाद गरेका थिए।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'nepali',
    chapter: 'साहित्य',
    year: 2075,
    source: 'seed',
    tags: ['भानुभक्त', 'आदिकवि', 'नेपाली-साहित्य'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-029',
    text: '"सन्धि" विच्छेद गर्नुहोस् — "नदी + इला = ?"',
    options: [
      { id: 'A', text: 'नदीला', isCorrect: false },
      { id: 'B', text: 'नदिला', isCorrect: false },
      { id: 'C', text: 'नदीयिला', isCorrect: true },
      { id: 'D', text: 'नदीयला', isCorrect: false },
    ],
    explanation: '"नदी + इला" गर्दा दीर्घ सन्धि हुन्छ। "नदी" को अन्त्यको "ई" र "इला" को आरम्भको "इ" मिलेर "ईयि" हुन्छ, त्यसैले "नदीयिला" हुन्छ। यो दीर्घ सन्धिको उदाहरण हो।',
    type: 'mcq',
    difficulty: 'hard',
    subject: 'nepali',
    chapter: 'व्याकरण',
    year: 2077,
    source: 'seed',
    tags: ['सन्धि', 'विच्छेद', 'दीर्घ सन्धि', 'व्याकरण'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-030',
    text: '"गोरखाली पात्र" कुन पत्रिका हो?',
    options: [
      { id: 'A', text: 'मोदर्न रिभ्यु', isCorrect: false },
      { id: 'B', text: 'शारदा', isCorrect: true },
      { id: 'C', text: 'माधव', isCorrect: false },
      { id: 'D', text: 'विजय', isCorrect: false },
    ],
    explanation: 'शारदा नेपालको पहिलो साहित्यिक पत्रिका थियो जसलाई गोरखाली पात्र भनिन्थ्यो। यो प्रसिद्ध पत्रकार र साहित्यकार शम्भु प्रसाद ढुंगेलले स्थापना गरेका थिए।',
    type: 'mcq',
    difficulty: 'hard',
    subject: 'nepali',
    chapter: 'साहित्य',
    year: 2075,
    source: 'seed',
    tags: ['शारदा', 'पत्रिका', 'नेपाली-साहित्य'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },

  // ═══════════════════════════════════════════════════════════════
  // CURRENT AFFAIRS — 10 Questions (seed-031 to seed-040)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'seed-031',
    text: 'नेपालको संघीय संरचनामा कति वटा प्रदेश छन्?',
    options: [
      { id: 'A', text: '५', isCorrect: false },
      { id: 'B', text: '६', isCorrect: false },
      { id: 'C', text: '७', isCorrect: true },
      { id: 'D', text: '८', isCorrect: false },
    ],
    explanation: 'संविधान २०७२ अनुसार नेपालमा ७ वटा प्रदेशहरू छन्। यी प्रदेशहरू भौगोलिक, जनसांख्यिक र आर्थिक आधारमा विभाजित छन्।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'current-affairs',
    chapter: 'National',
    year: 2075,
    source: 'seed',
    tags: ['प्रदेश', 'संघीय संरचना', 'संविधान-२०७२'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-032',
    text: 'नेपालको प्रथम राष्ट्रपति को हुन्?',
    options: [
      { id: 'A', text: 'रामचन्द्र पौडेल', isCorrect: false },
      { id: 'B', text: 'विद्यादेवी भण्डारी', isCorrect: true },
      { id: 'C', text: 'रामवरण यादव', isCorrect: false },
      { id: 'D', text: 'पुष्पकमल दाहाल', isCorrect: false },
    ],
    explanation: 'बिद्यादेवी भण्डारी नेपालको प्रथम राष्ट्रपति हुन्। उहाँलाई संविधान २०७२ लागू भएपछि संसदले निर्वाचित गरेको थियो।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'current-affairs',
    chapter: 'National',
    year: 2075,
    source: 'seed',
    tags: ['राष्ट्रपति', 'विद्यादेवी भण्डारी', 'प्रथम'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-033',
    text: 'नेपालमा महिला प्रधानमन्त्री भएकी पहिलो महिला को हुन्?',
    options: [
      { id: 'A', text: 'विश्वा देवी', isCorrect: true },
      { id: 'B', text: 'सुशीला कोइराला', isCorrect: false },
      { id: 'C', text: 'सावित्री भण्डारी', isCorrect: false },
      { id: 'D', text: 'ओनसरी घर्ती', isCorrect: false },
    ],
    explanation: 'विश्वा देवी नेपालको पहिलो महिला प्रधानमन्त्री हुन्। उहाँले वि.सं. २०४७ मा प्रधानमन्त्रीको रूपमा कार्यभार सम्हालेकी थिइन्।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'current-affairs',
    chapter: 'National',
    year: 2076,
    source: 'seed',
    tags: ['महिला प्रधानमन्त्री', 'विश्वा देवी', 'इतिहास'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-034',
    text: 'नेपालको सकल आन्तरिक उत्पादन (GDP) मुख्यतया कुन क्षेत्रबाट आउँछ?',
    options: [
      { id: 'A', text: 'कृषि क्षेत्र', isCorrect: true },
      { id: 'B', text: 'उद्योग क्षेत्र', isCorrect: false },
      { id: 'C', text: 'सेवा क्षेत्र', isCorrect: false },
      { id: 'D', text: 'पर्यटन क्षेत्र', isCorrect: false },
    ],
    explanation: 'नेपालको GDP मा कृषि क्षेत्रको ठूलो योगदान छ, यद्यपि सेवा क्षेत्र पनि बढ्दो छ। नेपालको अर्थतन्त्रमा कृषि अझै मुख्य पेशा हो।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'current-affairs',
    chapter: 'Economy',
    year: 2078,
    source: 'seed',
    tags: ['GDP', 'कृषि', 'अर्थतन्त्र', 'नेपाल-अर्थ'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-035',
    text: 'नेपालको प्रमुख व्यापारिक गन्तव्य कुन मुलुक हो?',
    options: [
      { id: 'A', text: 'चीन', isCorrect: false },
      { id: 'B', text: 'भारत', isCorrect: true },
      { id: 'C', text: 'अमेरिका', isCorrect: false },
      { id: 'D', text: 'जापान', isCorrect: false },
    ],
    explanation: 'भारत नेपालको सबैभन्दा ठूलो व्यापारिक साझेदार हो। नेपालको आयात र निर्यातको ठूलो हिस्सा भारतसँग हुन्छ।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'current-affairs',
    chapter: 'Economy',
    year: 2078,
    source: 'seed',
    tags: ['व्यापार', 'भारत', 'निर्यात', 'आयात'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-036',
    text: 'नेपालमा संघीय लोकसेवा आयोगको अध्यक्षको पदमा हाल (२०८०) को हुन्?',
    options: [
      { id: 'A', text: 'डा. उमेशकुमार शर्मा', isCorrect: true },
      { id: 'B', text: 'प्रो. डा. केदारबहादुर', isCorrect: false },
      { id: 'C', text: 'दिलकुमार ज्ञवाली', isCorrect: false },
      { id: 'D', text: 'प्रकाशकुमार थापा', isCorrect: false },
    ],
    explanation: 'संघीय लोकसेवा आयोगको अध्यक्षमा डा. उमेशकुमार शर्मा छन्। लोकसेवा आयोग नेपालको निजामती सेवा मा काम गर्ने मुख्य संस्था हो।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'current-affairs',
    chapter: 'National',
    year: 2080,
    source: 'seed',
    tags: ['लोकसेवा आयोग', 'अध्यक्ष', 'निजामती सेवा'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-037',
    text: 'नेपालको परराष्ट्र नीतिको मूल सिद्धान्त के हो?',
    options: [
      { id: 'A', text: 'गैर-गठबन्धन', isCorrect: true },
      { id: 'B', text: 'गठबन्धन', isCorrect: false },
      { id: 'C', text: 'उदासीन', isCorrect: false },
      { id: 'D', text: 'पक्षपाती', isCorrect: false },
    ],
    explanation: 'नेपालको परराष्ट्र नीतिको मूल सिद्धान्त गैर-गठबन्धन (Non-alignment) हो। यो सिद्धान्त अन्तर्राष्ट्रिय सम्बन्धमा तटस्थता कायम राख्ने नीति हो।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'current-affairs',
    chapter: 'International',
    year: 2077,
    source: 'seed',
    tags: ['परराष्ट्र नीति', 'गैर-गठबन्धन', 'अन्तर्राष्ट्रिय'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-038',
    text: 'बहुदलीय प्रजातन्त्र नेपालमा कहिले स्थापना भयो?',
    options: [
      { id: 'A', text: 'वि.सं. २०४६', isCorrect: true },
      { id: 'B', text: 'वि.सं. २०४७', isCorrect: false },
      { id: 'C', text: 'वि.सं. २०५०', isCorrect: false },
      { id: 'D', text: 'वि.सं. २०५४', isCorrect: false },
    ],
    explanation: 'नेपालमा बहुदलीय प्रजातन्त्र वि.सं. २०४६ सालमा जनआन्दोलन पछि स्थापना भयो। यो आन्दोलनले राजतन्त्रमाथि बहुदलीय प्रजातन्त्र स्थापना गर्यो।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'current-affairs',
    chapter: 'National',
    year: 2076,
    source: 'seed',
    tags: ['बहुदलीय प्रजातन्त्र', 'जनआन्दोलन', '२०४६'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-039',
    text: 'नेपालको दोस्रो संविधान निर्वाचन कबको भयो?',
    options: [
      { id: 'A', text: 'वि.सं. २०७०', isCorrect: true },
      { id: 'B', text: 'वि.सं. २०७२', isCorrect: false },
      { id: 'C', text: 'वि.सं. २०६५', isCorrect: false },
      { id: 'D', text: 'वि.सं. २०७४', isCorrect: false },
    ],
    explanation: 'नेपालको संविधानसभा निर्वाचन वि.सं. २०७० मा भयो। यस निर्वाचनले संविधान २०७२ निर्माण गर्ने संविधान सभाको गठन गर्‍यो।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'current-affairs',
    chapter: 'National',
    year: 2077,
    source: 'seed',
    tags: ['संविधानसभा', 'निर्वाचन', '२०७०'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-040',
    text: 'BRI (Belt and Road Initiative) अन्तर्गत नेपालमा कुन परियोजना मुख्य छ?',
    options: [
      { id: 'A', text: 'केरुङ-रसुवा राजमार्ग', isCorrect: false },
      { id: 'B', text: 'त्रिभुवन अन्तर्राष्ट्रिय विमानस्थल विस्तार', isCorrect: false },
      { id: 'C', text: 'पोखरा अन्तर्राष्ट्रिय विमानस्थल', isCorrect: true },
      { id: 'D', text: 'मेलम्ची खानेपानी आयोजना', isCorrect: false },
    ],
    explanation: 'BRI अन्तर्गत नेपालमा पोखरा अन्तर्राष्ट्रिय विमानस्थल निर्माण परियोजना चीनको सहयोगमा भएको मुख्य परियोजना हो। यो चीनको Belt and Road Initiative को अंश हो।',
    type: 'mcq',
    difficulty: 'hard',
    subject: 'current-affairs',
    chapter: 'International',
    year: 2080,
    source: 'seed',
    tags: ['BRI', 'चीन', 'पोखरा विमानस्थल', 'अन्तर्राष्ट्रिय'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },

  // ═══════════════════════════════════════════════════════════════
  // GOVERNANCE / PUBLIC ADMIN — 10 Questions (seed-041 to seed-050)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'seed-041',
    text: 'नेपालमा निजामती सेवाको दरबन्दी कति स्तरको छ?',
    options: [
      { id: 'A', text: '५', isCorrect: false },
      { id: 'B', text: '६', isCorrect: false },
      { id: 'C', text: '७', isCorrect: false },
      { id: 'D', text: '८', isCorrect: true },
    ],
    explanation: 'नेपालको निजामती सेवामा कुल ८ स्तरको दरबन्दी छ: सहायक, प्रशासक, नायब सचिव, उपसचिव, संयुक्त सचिव, सचिव, विशेष सचिव, र मुख्य सचिव।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'governance',
    chapter: 'निजामती सेवा',
    year: 2076,
    source: 'seed',
    tags: ['निजामती सेवा', 'दरबन्दी', 'लोकसेवा'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-042',
    text: 'नेपालमा संघीय लोकसेवा आयोगले कुन तहको परीक्षा सञ्चालन गर्दैन?',
    options: [
      { id: 'A', text: 'कार्यालय सहायक (गैर-प्रवेशिका)', isCorrect: false },
      { id: 'B', text: 'नायब सचिव (विशेष)', isCorrect: false },
      { id: 'C', text: 'सहायक सचिव (संवैधानिक)', isCorrect: false },
      { id: 'D', text: 'सचिव (मन्त्रिपरिषद्ले नियुक्त)', isCorrect: true },
    ],
    explanation: 'सचिव तहको नियुक्ति मन्त्रिपरिषद्ले गर्छ। लोकसेवा आयोगले सचिव तहको परीक्षा सञ्चालन गर्दैन। यो संविधान २०७२ को धारा २४४ अनुसारको व्यवस्था हो।',
    type: 'mcq',
    difficulty: 'hard',
    subject: 'governance',
    chapter: 'लोकसेवा',
    year: 2078,
    source: 'seed',
    tags: ['लोकसेवा आयोग', 'सचिव', 'नियुक्ति'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-043',
    text: 'नेपालको लोकसेवाको खुला प्रतियोगितात्मक लिखित परीक्षामा पूर्णाङ्क कति हुन्छ?',
    options: [
      { id: 'A', text: '१००', isCorrect: true },
      { id: 'B', text: '८०', isCorrect: false },
      { id: 'C', text: '१५०', isCorrect: false },
      { id: 'D', text: '५०', isCorrect: false },
    ],
    explanation: 'लोकसेवा आयोगको खुला प्रतियोगितात्मक लिखित परीक्षामा सामान्यतया १०० अंकको परीक्षा हुन्छ। MCQ आधारित यो परीक्षामा २ घण्टा समय दिइन्छ।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'governance',
    chapter: 'लोकसेवा',
    year: 2079,
    source: 'seed',
    tags: ['लोकसेवा परीक्षा', 'MCQ', 'खुला-प्रतियोगिता'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-044',
    text: 'नेपालमा शासन प्रणाली के हो?',
    options: [
      { id: 'A', text: 'संसदीय प्रणाली', isCorrect: false },
      { id: 'B', text: 'राष्ट्रपतीय प्रणाली', isCorrect: false },
      { id: 'C', text: 'अर्ध-राष्ट्रपतीय प्रणाली', isCorrect: true },
      { id: 'D', text: 'समाजवादी प्रणाली', isCorrect: false },
    ],
    explanation: 'नेपालमा संसदीय र प्रमुखको संयुक्त व्यवस्था भएको अर्ध-राष्ट्रपतीय प्रणाली छ। यहाँ प्रधानमन्त्री कार्यपालिका प्रमुख र राष्ट्रपति राज्य प्रमुख हुन्छन्।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'governance',
    chapter: 'शासन व्यवस्था',
    year: 2076,
    source: 'seed',
    tags: ['शासन प्रणाली', 'संसदीय', 'राष्ट्रपतीय'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-045',
    text: '"अच्छो शासन" (Good Governance) को अर्थमा कुन सिद्धान्त समावेश हुँदैन?',
    options: [
      { id: 'A', text: 'पारदर्शिता', isCorrect: false },
      { id: 'B', text: 'जवाफदेहिता', isCorrect: false },
      { id: 'C', text: 'भेदभाव', isCorrect: true },
      { id: 'D', text: 'नियमकानुकूलता', isCorrect: false },
    ],
    explanation: 'अच्छो शासनका सिद्धान्तहरूमा पारदर्शिता, जवाफदेहिता, सहभागिता, नियमकानुकूलता र समानता हुन्छन् तर भेदभाव समावेश हुँदैन।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'governance',
    chapter: 'शासन व्यवस्था',
    year: 2077,
    source: 'seed',
    tags: ['अच्छो शासन', 'पारदर्शिता', 'जवाफदेहिता'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-046',
    text: 'नेपालमा कुन एक विधि अन्तर्गत स्थानीय सरकारलाई बजेट प्राप्त हुन्छ?',
    options: [
      { id: 'A', text: 'मध्यस्थता अनुदान', isCorrect: false },
      { id: 'B', text: 'समानुपातिक अनुदान', isCorrect: false },
      { id: 'C', text: 'विशेष अनुदान', isCorrect: false },
      { id: 'D', text: 'उपरोक्त सबै', isCorrect: true },
    ],
    explanation: 'स्थानीय सरकारलाई समानुपातिक अनुदान, मध्यस्थता अनुदान, सर्तसहित अनुदान, सर्वसाधारण अनुदान, र विशेष अनुदान गरी विभिन्न माध्यमबाट बजेट प्राप्त हुन्छ।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'governance',
    chapter: 'संघीय संरचना',
    year: 2078,
    source: 'seed',
    tags: ['स्थानीय सरकार', 'अनुदान', 'बजेट', 'वित्तीय-व्यवस्था'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-047',
    text: 'नेपालको राष्ट्रिय योजना आयोगको पूर्ण रूपमा संघीयकरण कब भयो?',
    options: [
      { id: 'A', text: 'वि.सं. २०७३', isCorrect: false },
      { id: 'B', text: 'वि.सं. २०७४', isCorrect: true },
      { id: 'C', text: 'वि.सं. २०७५', isCorrect: false },
      { id: 'D', text: 'वि.सं. २०७६', isCorrect: false },
    ],
    explanation: 'राष्ट्रिय योजना आयोगको संघीयकरण वि.सं. २०७४ मा भयो। यस अन्तर्गत संघीय, प्रदेश र स्थानीय स्तरमा योजना निर्माण प्रक्रिया सञ्चालन भइरहेको छ।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'governance',
    chapter: 'विकास योजना',
    year: 2077,
    source: 'seed',
    tags: ['राष्ट्रिय योजना आयोग', 'संघीयकरण', 'विकास-योजना'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-048',
    text: 'नेपालमा सार्वजनिक सेवाको सिद्धान्त कुन हो?',
    options: [
      { id: 'A', text: 'सरकारले आफ्नो इच्छाअनुसार काम गर्ने', isCorrect: false },
      { id: 'B', text: 'सरकारी सेवा सबै नागरिकको लागि समान हुने', isCorrect: true },
      { id: 'C', text: 'सेवा केवल बिजनेसमान चलाउने', isCorrect: false },
      { id: 'D', text: 'सेवामा नाफा कमाउने मुख्य उद्देश्य हुने', isCorrect: false },
    ],
    explanation: 'सार्वजनिक सेवाको मूल सिद्धान्त भनेको सबै नागरिकले समान रूपमा सेवा प्राप्त गर्न पाउनु हो। सरकारले सेवा नाफाको लागि नभएर नागरिकको कल्याणको लागि प्रदान गर्छ।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'governance',
    chapter: 'शासन व्यवस्था',
    year: 2076,
    source: 'seed',
    tags: ['सार्वजनिक सेवा', 'सेवा-सिद्धान्त', 'नागरिक'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-049',
    text: 'नेपालको संघीय मामिला तथा सामान्य प्रशासन मन्त्रालयको स्थापना कब भयो?',
    options: [
      { id: 'A', text: 'वि.सं. २०७४', isCorrect: true },
      { id: 'B', text: 'वि.सं. २०७५', isCorrect: false },
      { id: 'C', text: 'वि.सं. २०७३', isCorrect: false },
      { id: 'D', text: 'वि.सं. २०७६', isCorrect: false },
    ],
    explanation: 'संघीय मामिला तथा सामान्य प्रशासन मन्त्रालयको स्थापना वि.सं. २०७४ मा संविधान लागू भएपछि संघीय सरकारको संरचनामा भयो।',
    type: 'mcq',
    difficulty: 'medium',
    subject: 'governance',
    chapter: 'शासन व्यवस्था',
    year: 2078,
    source: 'seed',
    tags: ['मन्त्रालय', 'संघीय सरकार', 'स्थापना'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-050',
    text: 'नेपालमा लोकसेवा आयोग अन्तर्गत गार्हो सेवाको उमेर सीमा कति वर्ष हो?',
    options: [
      { id: 'A', text: '२५ देखि ४० वर्ष', isCorrect: false },
      { id: 'B', text: '२१ देखि ३५ वर्ष', isCorrect: true },
      { id: 'C', text: '२५ देखि ४५ वर्ष', isCorrect: false },
      { id: 'D', text: '१८ देखि ३५ वर्ष', isCorrect: false },
    ],
    explanation: 'लोकसेवा आयोग अन्तर्गत खुला प्रतियोगितात्मक परीक्षामा सहभागी हुनका लागि न्यूनतम २१ वर्ष र अधिकतम ३५ वर्ष उमेर सीमा छ।',
    type: 'mcq',
    difficulty: 'easy',
    subject: 'governance',
    chapter: 'लोकसेवा',
    year: 2079,
    source: 'seed',
    tags: ['लोकसेवा', 'उमेर सीमा', 'परीक्षा'],
    status: 'approved',
    reportCount: 0,
    createdAt: now,
    updatedAt: now,
  },
]

/**
 * Get seed questions by subject
 */
export function getSeedQuestionsBySubject(
  subject: string
): Question[] {
  return SEED_QUESTIONS.filter((q) => q.subject === subject)
}

/**
 * Get all seed question IDs
 */
export function getSeedQuestionIds(): string[] {
  return SEED_QUESTIONS.map((q) => q.id)
}

/**
 * Seed the database with default questions.
 * Checks if data already exists before inserting.
 * Returns the number of questions created.
 */
export async function seedDatabase(): Promise<{ created: number }> {
  const db = await initDB()

  // Check if data already exists
  const count = await db.count('questions')
  if (count > 0) {
    return { created: 0 }
  }

  // Insert seed questions in a transaction
  const tx = db.transaction('questions', 'readwrite')
  let created = 0

  for (const question of SEED_QUESTIONS) {
    // Check if this specific question already exists (by id)
    const existing = await tx.store.get(question.id)
    if (!existing) {
      await tx.store.put(question)
      created++
    }
  }

  await tx.done
  return { created }
}
